import {initializeApp,deleteApp} from "https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js";
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,deleteUser,signOut,EmailAuthProvider,reauthenticateWithCredential} from "https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js";
import {getFirestore,collection,doc,getDoc,getDocs,query,where,setDoc,updateDoc,deleteDoc,deleteField,writeBatch,serverTimestamp} from "https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js";
const config={apiKey:"AIzaSyDaNbVpvkGov4vtabbk-bAWOpb7nDpmzrA",authDomain:"goregister-7394b.firebaseapp.com",projectId:"goregister-7394b"};
const app=initializeApp(config),auth=getAuth(app),db=getFirestore(app),root=document.querySelector("#adminApp");
let companies=[],users=[],administrators=[],section="companies",editingCompany=null,editingAdministrator=null,editingUser=null,companyModalOpen=false,administratorModalOpen=false,userModalOpen=false,confirming=null,adminTool=null,adminToolError="",message="",administratorLoadError="";
const esc=value=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll('"',"&quot;");
const normalized=value=>String(value||"").trim().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const identifierDigits=value=>String(value||"").replace(/\D/g,"");
const normalizedCompanyIdentifier=value=>{const clean=String(value||"").trim();return clean&&/^[\d\s./-]+$/.test(clean)?identifierDigits(clean):normalized(clean)};
const cleanText=(value,maxLength=160)=>String(value||"").replace(/\s+/g," ").trim().slice(0,maxLength);
const cleanMultiline=(value,maxLength)=>String(value||"").replace(/\r\n?/g,"\n").split("\n").map(line=>line.replace(/[ \t]+/g," ").trim()).join("\n").replace(/\n{3,}/g,"\n\n").trim().slice(0,maxLength);
const formatCnae=value=>{const digits=identifierDigits(value);return digits.length===7?`${digits.slice(0,4)}-${digits.slice(4,5)}/${digits.slice(5)}`:cleanText(value,14)};
const validCpf=value=>{const digits=identifierDigits(value);if(digits.length!==11||/^(\d)\1+$/.test(digits))return false;const check=limit=>{let sum=0;for(let index=0;index<limit;index++)sum+=Number(digits[index])*(limit+1-index);const remainder=(sum*10)%11;return Number(digits[limit])===(remainder===10?0:remainder)};return check(9)&&check(10)};
const validCnpj=value=>{const digits=identifierDigits(value);if(digits.length!==14||/^(\d)\1+$/.test(digits))return false;const check=length=>{const weights=length===12?[5,4,3,2,9,8,7,6,5,4,3,2]:[6,5,4,3,2,9,8,7,6,5,4,3,2],sum=weights.reduce((total,weight,index)=>total+Number(digits[index])*weight,0),remainder=sum%11;return Number(digits[length])===(remainder<2?0:11-remainder)};return check(12)&&check(13)};
const validCompanyIdentifier=value=>{const digits=identifierDigits(value);return digits.length===11?validCpf(digits):digits.length===14&&validCnpj(digits)};
function normalizeOpeningDate(value){const clean=cleanText(value,10);if(!clean)return "";const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(clean);if(!match)throw Error("Informe uma data de abertura válida.");const year=Number(match[1]),month=Number(match[2]),day=Number(match[3]),parsed=new Date(year,month-1,day),today=new Date(),todayStart=new Date(today.getFullYear(),today.getMonth(),today.getDate());if(parsed.getFullYear()!==year||parsed.getMonth()!==month-1||parsed.getDate()!==day)throw Error("Informe uma data de abertura válida.");if(parsed>todayStart)throw Error("A data de abertura não pode estar no futuro.");return clean}
const firstCompanyValue=(company,keys)=>{for(const key of keys){const value=company?.[key];if(value!==undefined&&value!==null&&String(value).trim())return value}return ""};
const documentFields=(value,excluded=[])=>Object.fromEntries(Object.entries(value||{}).filter(([key])=>!["id","companyId","createdAt","updatedAt",...excluded].includes(key)));
const legacyOpeningDate=value=>{if(!value)return "";if(typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const parsed=value?.toDate?.()||new Date(value);if(Number.isNaN(parsed.getTime()))return "";const year=parsed.getFullYear(),month=String(parsed.getMonth()+1).padStart(2,"0"),day=String(parsed.getDate()).padStart(2,"0");return `${year}-${month}-${day}`};
function legacyCompanyProfile(company){return{legalName:firstCompanyValue(company,["legalName","corporateName","razaoSocial","razao_social"]),unitName:firstCompanyValue(company,["unitName","branchName","filial","unidade"]),stateRegistration:firstCompanyValue(company,["stateRegistration","inscricaoEstadual","inscricao_estadual"]),municipalRegistration:firstCompanyValue(company,["municipalRegistration","inscricaoMunicipal","inscricao_municipal"]),cnae:firstCompanyValue(company,["cnae","mainCnae","cnaePrincipal"]),taxRegime:firstCompanyValue(company,["taxRegime","regimeTributario","regime_tributario"]),email:firstCompanyValue(company,["email","companyEmail","contactEmail"]),website:firstCompanyValue(company,["website","site","url"]),logoUrl:firstCompanyValue(company,["logoUrl","logoURL","logo_url"]),responsibleName:firstCompanyValue(company,["responsibleName","legalRepresentative","responsavel","nomeResponsavel"]),responsibleRole:firstCompanyValue(company,["responsibleRole","responsiblePosition","cargoResponsavel","cargo"]),openingDate:legacyOpeningDate(firstCompanyValue(company,["openingDate","dataAbertura","data_abertura"])),pixKey:firstCompanyValue(company,["pixKey","chavePix","chave_pix"]),institutionalNotes:firstCompanyValue(company,["institutionalNotes","observacoesInstitucionais","observacoes_institucionais"])}}
function legacyReceiptSettings(company){return{socialMedia:firstCompanyValue(company,["socialMedia","socialNetworks","redeSocial","redesSociais"]),receiptMessage:firstCompanyValue(company,["receiptMessage","mensagemRecibo","mensagem_recibo"]),exchangePolicy:firstCompanyValue(company,["exchangePolicy","politicaTroca","politica_troca"])}}
function normalizeWebsite(value){const clean=cleanText(value,240);if(!clean)return "";const candidate=/^https?:\/\//i.test(clean)?clean:`https://${clean}`;let parsed;try{parsed=new URL(candidate)}catch{throw Error("Informe um site válido, como empresa.com.br.")}if(!["http:","https:"].includes(parsed.protocol)||!parsed.hostname.includes("."))throw Error("Informe um site válido, como empresa.com.br.");return parsed.toString().replace(/\/$/,"")}
function normalizeLogoUrl(value){const clean=cleanText(value,500);if(!clean)return "";let parsed;try{parsed=new URL(clean)}catch{throw Error("Informe uma URL HTTPS válida para o logotipo.")}if(parsed.protocol!=="https:"||!parsed.hostname.includes("."))throw Error("A URL do logotipo deve começar com https://.");return parsed.toString()}
function companyProfileFromForm(form){const email=cleanText(form.email,160).toLowerCase(),website=normalizeWebsite(form.website),logoUrl=normalizeLogoUrl(form.logoUrl),openingDate=normalizeOpeningDate(form.openingDate),cnae=formatCnae(form.cnae);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error("Informe um e-mail comercial válido.");if(cnae&&identifierDigits(cnae).length!==7)throw Error("O CNAE deve conter 7 números.");return{legalName:cleanText(form.legalName,180),unitName:cleanText(form.unitName,120),stateRegistration:cleanText(form.stateRegistration,40),municipalRegistration:cleanText(form.municipalRegistration,40),cnae,taxRegime:cleanText(form.taxRegime,80),email,website,logoUrl,responsibleName:cleanText(form.responsibleName,160),responsibleRole:cleanText(form.responsibleRole,100),openingDate,pixKey:cleanText(form.pixKey,180),institutionalNotes:cleanMultiline(form.institutionalNotes,1000)}}
function receiptSettingsFromForm(form){return{socialMedia:cleanText(form.socialMedia,240),receiptMessage:cleanMultiline(form.receiptMessage,500),exchangePolicy:cleanMultiline(form.exchangePolicy,1200)}}
const operationalCollections=["products","sales","categories","suppliers","cash_registers","financial_entries","financial_exits","stock_movements","settings"];
const randomToken=()=>{const bytes=new Uint8Array(24);crypto.getRandomValues(bytes);return [...bytes].map(byte=>byte.toString(16).padStart(2,"0")).join("")};
const sha256Hex=async value=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))].map(byte=>byte.toString(16).padStart(2,"0")).join("");
const emailAliasId=async(companyId,email)=>`${companyId}__email__${await sha256Hex(normalized(email))}`;
const internalAuthEmail=async(companyId,email)=>`${companyId}.${(await sha256Hex(`${normalized(email)}:${randomToken()}`)).slice(0,24)}@users.goregister.app`;
async function resetCancellationPasswordDirect(companyId,password){const salt=randomToken(),hash=await sha256Hex(`${salt}:${password}`);await setDoc(doc(db,"companies",companyId,"settings","cancellation"),{id:"cancellation",empresa_id:companyId,passwordHash:`sha256$${salt}$${hash}`,updatedAt:Date.now(),updatedByPlatformAdmin:auth.currentUser.uid},{merge:true})}
async function clearCompanyDataDirect(companyId){let deletedDocuments=0;for(const collectionName of operationalCollections){const snapshot=await getDocs(collection(db,"companies",companyId,collectionName));for(let offset=0;offset<snapshot.docs.length;offset+=500){const batch=writeBatch(db);snapshot.docs.slice(offset,offset+500).forEach(item=>batch.delete(item.ref));await batch.commit()}deletedDocuments+=snapshot.size}await setDoc(doc(db,"companies",companyId),{dataClearedAt:serverTimestamp(),dataClearedBy:auth.currentUser.uid,updatedAt:serverTimestamp()},{merge:true});return deletedDocuments}
async function verifyPlatformAdministrator(email,password){const currentUser=auth.currentUser,cleanEmail=String(email||"").trim().toLowerCase();if(!currentUser||normalized(currentUser.email)!==normalized(cleanEmail))throw Error("E-mail ou senha do administrador do painel inválidos.");try{await reauthenticateWithCredential(currentUser,EmailAuthProvider.credential(cleanEmail,String(password||"")))}catch{throw Error("E-mail ou senha do administrador do painel inválidos.")}}
const companyName=id=>companies.find(item=>item.id===id)?.name||"Empresa não encontrada";
const roleLabel=role=>({MASTER_ADMIN:"Administrador mestre",ADMIN:"Administrador",OPERATOR:"Operador"}[role]||role||"-");
function renderLogin(error=""){root.innerHTML=`<main class="login-shell"><form class="login-card" id="login"><h1>Administração</h1><p class="muted">Gerenciamento da plataforma GO REGISTER</p><label class="field"><span>E-mail</span><span class="input-wrap"><input name="email" type="email" required></span></label><label class="field"><span>Senha</span><span class="input-wrap"><input name="password" type="password" required></span></label><p class="error">${esc(error)}</p><button class="btn full">Entrar</button></form></main>`;document.querySelector("#login").onsubmit=async event=>{event.preventDefault();const form=new FormData(event.currentTarget);try{await signInWithEmailAndPassword(auth,form.get("email"),form.get("password"))}catch{renderLogin("Credenciais administrativas inválidas.")}}}
async function syncCompanyUserAliases(){const aliases=[];for(const user of users){const companyId=String(user.companyId||user.empresa_id||""),username=normalized(user.username),email=String(user.email||"").trim().toLowerCase(),authEmail=String(user.authEmail||user.email||"").trim();if(!companyId||!username||!authEmail)continue;const payload={empresa_id:companyId,uid:user.uid,email:authEmail,username:user.username,syncedFromCompanyUsers:true,updatedAt:serverTimestamp()};aliases.push([`${companyId}__${username}`,payload]);if(email)aliases.push([await emailAliasId(companyId,email),{...payload,kind:"email"}])}for(let offset=0;offset<aliases.length;offset+=400){const batch=writeBatch(db);aliases.slice(offset,offset+400).forEach(([id,payload])=>batch.set(doc(db,"login_aliases",id),payload,{merge:true}));await batch.commit()}}
async function load(successMessage=""){message=successMessage||"Carregando dados...";administratorLoadError="";render();try{const companySnapshot=await getDocs(collection(db,"companies")),baseCompanies=companySnapshot.docs.map(item=>({...item.data(),id:item.id,companyId:item.id})),[profileSnapshots,receiptSnapshots]=await Promise.all([Promise.all(baseCompanies.map(company=>getDoc(doc(db,"companies",company.companyId,"company_profile","official")))),Promise.all(baseCompanies.map(company=>getDoc(doc(db,"companies",company.companyId,"receipt_settings","official"))))]);companies=baseCompanies.map((company,index)=>{const rawProfile=profileSnapshots[index].exists()?profileSnapshots[index].data():legacyCompanyProfile(company),profile=documentFields(rawProfile,["socialMedia","receiptMessage","exchangePolicy"]),receiptSource={...company,...rawProfile},rawReceipt=receiptSnapshots[index].exists()?receiptSnapshots[index].data():legacyReceiptSettings(receiptSource),receiptSettings=documentFields(rawReceipt);return{...company,profile,receiptSettings}}).sort((a,b)=>String(a.name).localeCompare(String(b.name)));const userSnapshots=await Promise.all(companies.map(company=>getDocs(collection(db,"companies",company.companyId,"users"))));users=userSnapshots.flatMap((snapshot,index)=>snapshot.docs.map(item=>({...item.data(),uid:item.id,empresa_id:companies[index].companyId,companyId:companies[index].companyId})));await syncCompanyUserAliases();message=successMessage}catch(error){message=error.message||"Falha ao carregar as empresas e seus usuários.";render();return}try{const adminSnapshot=await getDocs(collection(db,"platform_admins"));administrators=adminSnapshot.docs.map(item=>({uid:item.id,...item.data()})).sort((a,b)=>String(a.name||a.email).localeCompare(String(b.name||b.email)))}catch(error){administrators=[];administratorLoadError="Não foi possível carregar os administradores. Publique as regras atualizadas do Firestore."}render()}
function date(value){const parsed=value?.toDate?.()||new Date(value||0);return Number.isNaN(parsed.getTime())?"-":parsed.toLocaleDateString("pt-BR")}
async function createAccount({password,username,empresa_id,role="OPERATOR",isActive=true}){const company=companies.find(item=>item.id===empresa_id);if(!company)throw Error("Selecione uma empresa válida.");const cleanUsername=String(username||"").trim();if(cleanUsername.length<3)throw Error("O nome de usuário deve ter pelo menos 3 caracteres.");if(users.some(item=>item.empresa_id===empresa_id&&normalized(item.username)===normalized(cleanUsername)))throw Error("Este nome de usuário já está sendo usado nesta empresa.");const authEmail=await internalAuthEmail(empresa_id,cleanUsername),secondary=initializeApp(config,`create-user-${Date.now()}`),secondaryAuth=getAuth(secondary);let createdUser=null;try{createdUser=(await createUserWithEmailAndPassword(secondaryAuth,authEmail,password)).user;const batch=writeBatch(db),timestamps={createdAt:serverTimestamp(),updatedAt:serverTimestamp()};batch.set(doc(db,"companies",empresa_id,"users",createdUser.uid),{empresa_id,companyId:empresa_id,email:null,authEmail,username:cleanUsername,role,isActive,companyName:company.name,...timestamps});batch.set(doc(db,"login_aliases",`${empresa_id}__${normalized(cleanUsername)}`),{empresa_id,uid:createdUser.uid,email:authEmail,username:cleanUsername,...timestamps});await batch.commit()}catch(error){if(createdUser)await deleteUser(createdUser).catch(()=>{});throw error}finally{await signOut(secondaryAuth).catch(()=>{});await deleteApp(secondary)}}
async function replaceUserPassword(user,password,oldUsername=user.username){const authEmail=await internalAuthEmail(user.empresa_id,user.email),emailLoginAlias=await emailAliasId(user.empresa_id,user.email),secondary=initializeApp(config,`reset-user-${Date.now()}`),secondaryAuth=getAuth(secondary);let createdUser=null;try{createdUser=(await createUserWithEmailAndPassword(secondaryAuth,authEmail,password)).user;const{uid,docId,authEmail:oldAuthEmail,...profile}=user,batch=writeBatch(db),oldAlias=`${user.empresa_id}__${normalized(oldUsername)}`,newAlias=`${user.empresa_id}__${normalized(user.username)}`;batch.set(doc(db,"companies",user.empresa_id,"users",createdUser.uid),{...profile,authEmail,updatedAt:serverTimestamp(),passwordUpdatedAt:serverTimestamp(),passwordUpdatedBy:auth.currentUser.uid});batch.delete(doc(db,"companies",user.empresa_id,"users",uid));if(oldAlias!==newAlias)batch.delete(doc(db,"login_aliases",oldAlias));batch.set(doc(db,"login_aliases",newAlias),{empresa_id:user.empresa_id,uid:createdUser.uid,email:authEmail,username:user.username,updatedAt:serverTimestamp()},{merge:true});batch.set(doc(db,"login_aliases",emailLoginAlias),{empresa_id:user.empresa_id,uid:createdUser.uid,email:authEmail,username:user.username,kind:"email",updatedAt:serverTimestamp()},{merge:true});await batch.commit()}catch(error){if(createdUser)await deleteUser(createdUser).catch(()=>{});throw error}finally{await signOut(secondaryAuth).catch(()=>{});await deleteApp(secondary)}}
async function saveCompany(formElement){
  const form=Object.fromEntries(new FormData(formElement)),name=cleanText(form.name,160),identifier=cleanText(form.identifier,24),address=cleanText(form.address,240),phone=cleanText(form.phone,32),identifierNormalized=normalizedCompanyIdentifier(identifier),profile=companyProfileFromForm(form),receiptSettings=receiptSettingsFromForm(form);
  if(name.length<2||!identifierNormalized||address.length<5||!phone)throw Error("Nome fantasia, CPF/CNPJ, endereço e telefone são obrigatórios.");
  const identifierChanged=!editingCompany||normalizedCompanyIdentifier(editingCompany.identifier||editingCompany.identifierNormalized)!==identifierNormalized,phoneDigits=identifierDigits(phone),phoneChanged=!editingCompany||identifierDigits(editingCompany.phone)!==phoneDigits;
  if(identifierChanged&&!validCompanyIdentifier(identifier))throw Error("Informe um CPF ou CNPJ válido.");
  if(phoneChanged&&![10,11].includes(phoneDigits.length))throw Error("O telefone deve conter DDD e 10 ou 11 números.");
  if(companies.find(item=>normalizedCompanyIdentifier(item.identifier||item.identifierNormalized)===identifierNormalized&&item.id!==editingCompany?.id))throw Error("Este identificador já está cadastrado.");
  const companyData={name,identifier,address,phone,identifierNormalized,isActive:editingCompany?form.isActive==="true":true,updatedAt:serverTimestamp()};
  if(editingCompany){
    const batch=writeBatch(db),profileRef=doc(db,"companies",editingCompany.id,"company_profile","official"),receiptSettingsRef=doc(db,"companies",editingCompany.id,"receipt_settings","official");
    batch.set(doc(db,"companies",editingCompany.id),companyData,{merge:true});
    batch.set(profileRef,{...profile,socialMedia:deleteField(),receiptMessage:deleteField(),exchangePolicy:deleteField(),id:"official",companyId:editingCompany.id,updatedAt:serverTimestamp()},{merge:true});
    batch.set(receiptSettingsRef,{...receiptSettings,id:"official",companyId:editingCompany.id,updatedAt:serverTimestamp()},{merge:true});
    users.filter(user=>user.empresa_id===editingCompany.id).forEach(user=>batch.update(doc(db,"companies",editingCompany.id,"users",user.uid),{companyName:name,updatedAt:serverTimestamp()}));
    return batch.commit()
  }
  const companyRef=doc(collection(db,"companies")),profileRef=doc(db,"companies",companyRef.id,"company_profile","official"),receiptSettingsRef=doc(db,"companies",companyRef.id,"receipt_settings","official");
  try{
    const batch=writeBatch(db);
    batch.set(companyRef,{...companyData,createdAt:serverTimestamp()});
    batch.set(profileRef,{...profile,id:"official",companyId:companyRef.id,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});
    batch.set(receiptSettingsRef,{...receiptSettings,id:"official",companyId:companyRef.id,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});
    await batch.commit();
    companies.push({id:companyRef.id,...companyData,profile,receiptSettings});
    await createAccount({password:form.adminPassword,username:form.adminUsername,empresa_id:companyRef.id,role:"MASTER_ADMIN"})
  }catch(error){
    companies=companies.filter(item=>item.id!==companyRef.id);
    const cleanupBatch=writeBatch(db);
    cleanupBatch.delete(receiptSettingsRef);
    cleanupBatch.delete(profileRef);
    cleanupBatch.delete(companyRef);
    await cleanupBatch.commit().catch(()=>{});
    throw error
  }
}
async function saveAdministrator(formElement){const form=Object.fromEntries(new FormData(formElement)),name=String(form.name||"").trim(),isActive=form.isActive==="true";if(name.length<2)throw Error("Informe o nome do administrador.");if(editingAdministrator){if(editingAdministrator.uid===auth.currentUser?.uid&&!isActive)throw Error("Você não pode desativar a conta administrativa que está usando.");return updateDoc(doc(db,"platform_admins",editingAdministrator.uid),{name,isActive,updatedAt:serverTimestamp()})}const email=String(form.email||"").trim().toLowerCase(),secondary=initializeApp(config,`create-platform-admin-${Date.now()}`);try{const uid=(await createUserWithEmailAndPassword(getAuth(secondary),email,String(form.password||""))).user.uid;await setDoc(doc(db,"platform_admins",uid),{name,email,isActive,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}finally{await signOut(getAuth(secondary)).catch(()=>{});await deleteApp(secondary)}}
async function saveUser(formElement){const form=Object.fromEntries(new FormData(formElement)),empresa_id=String(form.empresa_id||""),username=String(form.username||"").trim(),role=String(form.role||"OPERATOR"),isActive=form.isActive==="true",password=String(form.password||"");if(!companies.some(item=>item.id===empresa_id))throw Error("Selecione uma empresa válida.");if(username.length<3)throw Error("O nome de usuário deve ter pelo menos 3 caracteres.");if(users.some(item=>item.uid!==editingUser?.uid&&item.empresa_id===empresa_id&&normalized(item.username)===normalized(username)))throw Error("Este nome de usuário já está sendo usado nesta empresa.");if(!editingUser)return createAccount({password,username,empresa_id,role,isActive});if(password&&password.length<6)throw Error("A nova senha deve ter pelo menos 6 caracteres.");const oldAlias=`${editingUser.empresa_id}__${normalized(editingUser.username)}`,newAlias=`${empresa_id}__${normalized(username)}`,authEmail=editingUser.authEmail||editingUser.email,updatedUser={...editingUser,empresa_id,username,role,isActive,companyName:companyName(empresa_id)};if(password)return replaceUserPassword(updatedUser,password,editingUser.username);const batch=writeBatch(db);batch.set(doc(db,"companies",empresa_id,"users",editingUser.uid),{...updatedUser,updatedAt:serverTimestamp()},{merge:true});if(editingUser.empresa_id!==empresa_id)batch.delete(doc(db,"companies",editingUser.empresa_id,"users",editingUser.uid));if(oldAlias!==newAlias)batch.delete(doc(db,"login_aliases",oldAlias));batch.set(doc(db,"login_aliases",newAlias),{empresa_id,uid:editingUser.uid,email:authEmail,username,updatedAt:serverTimestamp()},{merge:true});if(editingUser.email)batch.set(doc(db,"login_aliases",await emailAliasId(empresa_id,editingUser.email)),{empresa_id,uid:editingUser.uid,email:authEmail,username,kind:"email",updatedAt:serverTimestamp()},{merge:true});await batch.commit()}
async function removeAdministrator(administrator){if(administrator.uid===auth.currentUser?.uid)throw Error("Você não pode excluir a conta administrativa que está usando.");await deleteDoc(doc(db,"platform_admins",administrator.uid));editingAdministrator=null;await load("Administrador excluído com sucesso.")}
async function removeCompany(company){const companyUsers=users.filter(user=>user.empresa_id===company.id);if(companyUsers.length>165)throw Error("Esta empresa possui usuários demais para exclusão direta. Exclua alguns usuários primeiro.");const emailAliases=await Promise.all(companyUsers.map(user=>emailAliasId(user.empresa_id,user.email))),batch=writeBatch(db);companyUsers.forEach((user,index)=>{batch.delete(doc(db,"login_aliases",`${user.empresa_id}__${normalized(user.username)}`));batch.delete(doc(db,"login_aliases",emailAliases[index]));batch.delete(doc(db,"companies",company.id,"users",user.uid))});batch.delete(doc(db,"companies",company.id,"receipt_settings","official"));batch.delete(doc(db,"companies",company.id,"company_profile","official"));batch.delete(doc(db,"companies",company.id));await batch.commit();editingCompany=null;await load("Empresa e seus vínculos foram excluídos com sucesso.")}
async function removeUser(user){const batch=writeBatch(db);batch.delete(doc(db,"companies",user.empresa_id,"users",user.uid));batch.delete(doc(db,"login_aliases",`${user.empresa_id}__${normalized(user.username)}`));batch.delete(doc(db,"login_aliases",await emailAliasId(user.empresa_id,user.email)));await batch.commit();editingUser=null;await load("Usuário excluído com sucesso.")}
function shell(content){return `<main class="admin-shell"><header class="admin-header"><div><h1>Administração</h1><p class="muted">Gerencie empresas e administradores da plataforma.</p></div><button class="btn secondary" id="logout">Sair</button></header><nav class="admin-nav"><button class="${section==="companies"?"active":""}" data-section="companies">Empresas</button><button class="${section==="administrators"?"active":""}" data-section="administrators">Administradores</button></nav>${content}</main>${message?`<aside class="admin-toast" role="status" aria-live="polite"><span>${esc(message)}</span><button type="button" data-dismiss-message aria-label="Fechar notificação">×</button></aside>`:""}`}
function companyView(){const rows=companies.map(company=>{const count=users.filter(user=>user.empresa_id===company.id).length;return `<tr><td><strong>${esc(company.name)}</strong></td><td>${esc(company.identifier)}</td><td><span class="status-dot ${company.isActive===false?"":"active"}"></span>${company.isActive===false?"Inativa":"Ativa"}</td><td>${count}</td><td>${date(company.createdAt)}</td><td class="admin-actions"><button class="btn secondary compact" data-edit-company="${company.id}">Editar</button><button class="btn secondary compact" data-toggle-company="${company.id}">${company.isActive===false?"Ativar":"Desativar"}</button><button class="btn danger compact" data-delete-company="${company.id}">Excluir</button></td></tr>`}).join("");return `<div class="section-heading"><div><h2>Empresas</h2><p class="muted">Cadastre e controle os acessos das empresas.</p></div><button class="btn" id="newCompany">Nova empresa</button></div><section class="panel admin-table"><table><thead><tr><th>Empresa</th><th>Identificador</th><th>Status</th><th>Usuários</th><th>Criação</th><th>Ações</th></tr></thead><tbody>${rows||'<tr><td colspan="6" class="admin-empty muted">Nenhuma empresa cadastrada.</td></tr>'}</tbody></table></section>${companyModalOpen?companyModal():""}`}
function companyModal(){
  const profile=editingCompany?.profile||{},receiptSettings=editingCompany?.receiptSettings||{},companyUsers=editingCompany?users.filter(user=>user.empresa_id===editingCompany.id):[];
  const userRows=companyUsers.map(user=>`<tr><td><strong>${esc(user.username||"-")}</strong><small>${esc(user.email||"-")}</small></td><td>${esc(roleLabel(user.role))}</td><td><span class="status-dot ${user.isActive===false?"":"active"}"></span>${user.isActive===false?"Inativo":"Ativo"}</td><td class="admin-actions"><button class="btn secondary compact" type="button" data-edit-company-user="${user.uid}">Editar</button><button class="btn danger compact" type="button" data-delete-company-user="${user.uid}">Excluir</button></td></tr>`).join("");
  return `<div class="admin-modal-backdrop" data-close-modal><section class="admin-modal admin-modal-wide company-modal" role="dialog" aria-modal="true" aria-labelledby="companyModalTitle"><button class="admin-modal-close" type="button" data-close-modal aria-label="Fechar">×</button><form class="admin-form" id="companyForm"><div class="company-modal-heading"><div><h2 id="companyModalTitle">${editingCompany?"Editar empresa":"Nova empresa"}</h2><p class="muted">Os dados profissionais são administrados exclusivamente por este painel.</p></div></div>
  <fieldset class="company-form-section"><legend>Identificação da empresa</legend><div class="company-form-grid">
    <label class="field"><span>Nome fantasia *</span><span class="input-wrap"><input name="name" maxlength="160" value="${esc(editingCompany?.name)}" required autofocus></span></label>
    <label class="field"><span>Razão social</span><span class="input-wrap"><input name="legalName" maxlength="180" value="${esc(profile.legalName)}"></span></label>
    <label class="field"><span>Filial ou unidade</span><span class="input-wrap"><input name="unitName" maxlength="120" value="${esc(profile.unitName)}" placeholder="Ex.: Matriz, Unidade Centro"></span></label>
    <label class="field"><span>CNPJ ou CPF *</span><span class="input-wrap"><input name="identifier" maxlength="18" inputmode="numeric" value="${esc(editingCompany?.identifier)}" placeholder="00.000.000/0000-00" required></span></label>
    <label class="field"><span>Data de abertura</span><span class="input-wrap"><input name="openingDate" type="date" value="${esc(profile.openingDate)}"></span></label>
    <label class="field"><span>Inscrição estadual</span><span class="input-wrap"><input name="stateRegistration" maxlength="40" value="${esc(profile.stateRegistration)}"></span></label>
    <label class="field"><span>Inscrição municipal</span><span class="input-wrap"><input name="municipalRegistration" maxlength="40" value="${esc(profile.municipalRegistration)}"></span></label>
    <label class="field"><span>CNAE principal</span><span class="input-wrap"><input name="cnae" maxlength="14" inputmode="numeric" placeholder="0000-0/00" value="${esc(profile.cnae)}"></span></label>
    <label class="field"><span>Regime tributário</span><span class="input-wrap"><input name="taxRegime" maxlength="80" list="taxRegimeOptions" value="${esc(profile.taxRegime)}" placeholder="Selecione ou digite"></span></label>
    <datalist id="taxRegimeOptions"><option value="MEI"><option value="Simples Nacional"><option value="Lucro Presumido"><option value="Lucro Real"><option value="Imune/Isenta"></datalist>
    <label class="field"><span>Status *</span><span class="input-wrap"><select name="isActive"><option value="true" ${editingCompany?.isActive===false?"":"selected"}>Ativa</option><option value="false" ${editingCompany?.isActive===false?"selected":""}>Inativa</option></select></span></label>
  </div></fieldset>
  <fieldset class="company-form-section"><legend>Contato e localização</legend><div class="company-form-grid">
    <label class="field field-wide"><span>Endereço completo *</span><span class="input-wrap"><input name="address" maxlength="240" value="${esc(editingCompany?.address)}" placeholder="Rua, número, complemento, bairro, cidade, UF e CEP" required></span></label>
    <label class="field"><span>Telefone *</span><span class="input-wrap"><input name="phone" type="tel" maxlength="20" inputmode="tel" value="${esc(editingCompany?.phone)}" placeholder="(00) 00000-0000" required></span></label>
    <label class="field"><span>E-mail comercial</span><span class="input-wrap"><input name="email" type="email" maxlength="160" autocomplete="email" value="${esc(profile.email)}"></span></label>
    <label class="field field-wide"><span>Site</span><span class="input-wrap"><input name="website" type="text" maxlength="240" inputmode="url" placeholder="empresa.com.br" value="${esc(profile.website)}"></span></label>
    <label class="field field-wide"><span>URL do logotipo</span><span class="input-wrap"><input name="logoUrl" type="url" maxlength="500" inputmode="url" placeholder="https://empresa.com.br/logo.png" value="${esc(profile.logoUrl)}"></span><small class="field-help">Use um endereço público e seguro iniciado por https://.</small></label>
    <label class="field field-wide"><span>Redes sociais</span><span class="input-wrap"><input name="socialMedia" maxlength="240" placeholder="Ex.: @empresa ou https://instagram.com/empresa" value="${esc(receiptSettings.socialMedia)}"></span></label>
  </div></fieldset>
  <fieldset class="company-form-section"><legend>Responsável e recebimentos</legend><div class="company-form-grid">
    <label class="field"><span>Nome do responsável</span><span class="input-wrap"><input name="responsibleName" maxlength="160" value="${esc(profile.responsibleName)}"></span></label>
    <label class="field"><span>Cargo ou função</span><span class="input-wrap"><input name="responsibleRole" maxlength="100" value="${esc(profile.responsibleRole)}"></span></label>
    <label class="field field-wide"><span>Chave Pix comercial</span><span class="input-wrap"><input name="pixKey" maxlength="180" value="${esc(profile.pixKey)}" autocomplete="off"></span></label>
  </div></fieldset>
  <fieldset class="company-form-section"><legend>Recibos e atendimento</legend><div class="company-form-grid">
    <label class="field field-wide"><span>Mensagem personalizada do recibo</span><span class="input-wrap textarea-wrap"><textarea name="receiptMessage" maxlength="500" rows="3" placeholder="Ex.: Agradecemos pela preferência!">${esc(receiptSettings.receiptMessage)}</textarea></span><small class="field-help">Texto opcional para o rodapé dos recibos.</small></label>
    <label class="field field-wide"><span>Política de troca, devolução ou garantia</span><span class="input-wrap textarea-wrap"><textarea name="exchangePolicy" maxlength="1200" rows="4" placeholder="Informe prazos e condições aplicáveis.">${esc(receiptSettings.exchangePolicy)}</textarea></span></label>
    <label class="field field-wide"><span>Observações institucionais</span><span class="input-wrap textarea-wrap"><textarea name="institutionalNotes" maxlength="1000" rows="3" placeholder="Informações adicionais sobre a empresa.">${esc(profile.institutionalNotes)}</textarea></span></label>
  </div></fieldset>
  ${editingCompany?"":`<fieldset class="company-form-section"><legend>Acesso inicial</legend><div class="company-form-grid"><label class="field"><span>Usuário do administrador *</span><span class="input-wrap"><input name="adminUsername" minlength="3" maxlength="80" required></span></label><label class="field"><span>Senha inicial *</span><span class="input-wrap"><input name="adminPassword" type="password" minlength="6" maxlength="128" autocomplete="new-password" required></span></label></div></fieldset>`}
  <div class="form-actions company-form-actions"><button class="btn" type="submit">Salvar empresa</button><button class="btn secondary" type="button" data-close-modal>Cancelar</button></div></form>
  ${editingCompany?`<div class="company-users"><div class="company-users-heading"><div><h3>Usuários da empresa</h3><p class="muted">Somente usuários vinculados a ${esc(editingCompany.name)}.</p></div><button class="btn" type="button" id="newCompanyUser">Novo usuário</button></div><div class="admin-table"><table><thead><tr><th>Usuário</th><th>Perfil</th><th>Status</th><th>Ações</th></tr></thead><tbody>${userRows||'<tr><td colspan="4" class="admin-empty muted">Nenhum usuário cadastrado nesta empresa.</td></tr>'}</tbody></table></div></div><div class="company-admin-tools"><h3>Controle administrativo</h3><p class="muted">Ações privilegiadas que não exigem as senhas atuais da empresa.</p><div class="form-actions"><button class="btn secondary" type="button" id="resetCancellationPassword">Redefinir senha de cancelamento</button><button class="btn danger" type="button" id="clearCompanyData">Limpar todos os dados da empresa</button></div><p class="field-help">A limpeza preserva a empresa, seus usuários e os dados profissionais, mas apaga produtos, vendas, caixa, históricos e configurações operacionais.</p></div>`:""}</section></div>`
}
function administratorView(){const rows=administrators.map(administrator=>`<tr><td><strong>${esc(administrator.name||"Administrador")}</strong></td><td>${esc(administrator.email||"-")}</td><td><span class="status-dot ${administrator.isActive===false?"":"active"}"></span>${administrator.isActive===false?"Inativo":"Ativo"}</td><td>${date(administrator.createdAt)}</td><td class="admin-actions"><button class="btn secondary compact" data-edit-administrator="${administrator.uid}">Editar</button><button class="btn danger compact" data-delete-administrator="${administrator.uid}">Excluir</button></td></tr>`).join("");return `<div class="section-heading"><div><h2>Administradores</h2><p class="muted">Gerencie somente as contas que acessam este site de administração.</p></div><button class="btn" id="newAdministrator">Novo administrador</button></div>${administratorLoadError?`<div class="notice">${esc(administratorLoadError)}</div>`:""}<section class="panel admin-table"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Status</th><th>Criação</th><th>Ações</th></tr></thead><tbody>${rows||'<tr><td colspan="5" class="admin-empty muted">Nenhum administrador cadastrado.</td></tr>'}</tbody></table></section>${administratorModalOpen?administratorModal():""}`}
function administratorModal(){return `<div class="admin-modal-backdrop" data-close-modal><section class="admin-modal" role="dialog" aria-modal="true" aria-labelledby="administratorModalTitle"><button class="admin-modal-close" type="button" data-close-modal aria-label="Fechar">×</button><form class="admin-form" id="administratorForm"><h2 id="administratorModalTitle">${editingAdministrator?"Editar administrador":"Novo administrador"}</h2><label class="field"><span>Nome</span><span class="input-wrap"><input name="name" value="${esc(editingAdministrator?.name)}" required autofocus></span></label><label class="field"><span>E-mail</span><span class="input-wrap"><input name="email" type="email" value="${esc(editingAdministrator?.email)}" ${editingAdministrator?"disabled":"required"}></span></label>${editingAdministrator?'<p class="field-help">O e-mail de autenticação não pode ser alterado por este painel.</p>':'<label class="field"><span>Senha inicial</span><span class="input-wrap"><input name="password" type="password" minlength="6" required></span></label>'}<label class="field"><span>Status</span><span class="input-wrap"><select name="isActive"><option value="true" ${editingAdministrator?.isActive===false?"":"selected"}>Ativo</option><option value="false" ${editingAdministrator?.isActive===false?"selected":""}>Inativo</option></select></span></label><div class="form-actions"><button class="btn" type="submit">Salvar administrador</button><button class="btn secondary" type="button" data-close-modal>Cancelar</button></div></form></section></div>`}
function companyUsersView(){const rows=users.map(user=>`<tr><td><strong>${esc(user.username||"-")}</strong><small>${esc(user.email||"-")}</small></td><td>${esc(companyName(user.empresa_id))}</td><td>${esc(roleLabel(user.role))}</td><td><span class="status-dot ${user.isActive===false?"":"active"}"></span>${user.isActive===false?"Inativo":"Ativo"}</td><td>${date(user.createdAt)}</td><td class="admin-actions"><button class="btn secondary compact" data-edit-user="${user.uid}">Editar</button><button class="btn danger compact" data-delete-user="${user.uid}">Excluir</button></td></tr>`).join("");return `<div class="section-heading"><div><h2>Usuários das empresas</h2><p class="muted">Gerencie as contas utilizadas pelas empresas cadastradas.</p></div><button class="btn" id="newUser" ${companies.length?"":"disabled"}>Novo usuário</button></div><section class="panel admin-table"><table><thead><tr><th>Usuário</th><th>Empresa</th><th>Perfil</th><th>Status</th><th>Criação</th><th>Ações</th></tr></thead><tbody>${rows||'<tr><td colspan="6" class="admin-empty muted">Nenhum usuário de empresa cadastrado.</td></tr>'}</tbody></table></section>${userModalOpen?userModal():""}`}
function userModal(){const selectedCompany=editingCompany||companies.find(company=>company.id===editingUser?.empresa_id);return `<div class="admin-modal-backdrop user-modal-layer" data-close-user-modal><section class="admin-modal" role="dialog" aria-modal="true" aria-labelledby="userModalTitle"><button class="admin-modal-close" type="button" data-close-user-modal aria-label="Fechar">×</button><form class="admin-form" id="userForm"><h2 id="userModalTitle">${editingUser?"Editar usuário":"Novo usuário"}</h2><p class="modal-context">Empresa: <strong>${esc(selectedCompany?.name)}</strong></p><input type="hidden" name="empresa_id" value="${esc(selectedCompany?.id)}"><label class="field"><span>Nome de usuário</span><span class="input-wrap"><input name="username" minlength="3" value="${esc(editingUser?.username)}" required autofocus></span></label>${editingUser?'<label class="field"><span>Nova senha</span><span class="input-wrap"><input name="password" type="password" minlength="6" maxlength="128" autocomplete="new-password" placeholder="Deixe em branco para manter a atual"></span></label><p class="field-help">Ao preencher, a senha atual será substituída imediatamente.</p>':'<label class="field"><span>Senha inicial</span><span class="input-wrap"><input name="password" type="password" minlength="6" maxlength="128" required></span></label>'}<label class="field"><span>Perfil</span><span class="input-wrap"><select name="role"><option value="OPERATOR" ${editingUser?.role==="OPERATOR"?"selected":""}>Operador</option><option value="ADMIN" ${editingUser?.role==="ADMIN"?"selected":""}>Administrador</option><option value="MASTER_ADMIN" ${editingUser?.role==="MASTER_ADMIN"?"selected":""}>Administrador mestre</option></select></span></label><label class="field"><span>Status</span><span class="input-wrap"><select name="isActive"><option value="true" ${editingUser?.isActive===false?"":"selected"}>Ativo</option><option value="false" ${editingUser?.isActive===false?"selected":""}>Inativo</option></select></span></label><div class="form-actions"><button class="btn" type="submit">Salvar usuário</button><button class="btn secondary" type="button" data-close-user-modal>Cancelar</button></div></form></section></div>`}
function confirmationModal(){if(!confirming)return "";const label=confirming.type==="company"?confirming.item.name:(confirming.item.name||confirming.item.username||confirming.item.email);if(confirming.type==="company")return `<div class="admin-modal-backdrop"><section class="admin-modal" role="alertdialog" aria-modal="true"><form class="admin-form" id="confirmCompanyDeleteForm"><h2>Excluir empresa</h2><p>Você está prestes a excluir <strong>${esc(label)}</strong> e seus vínculos.</p><p class="muted">Confirme as credenciais do administrador do painel. Esta ação não poderá ser desfeita.</p><label class="field"><span>E-mail do administrador do painel</span><span class="input-wrap"><input name="platformAdminEmail" type="email" autocomplete="username" required autofocus></span></label><label class="field"><span>Senha do administrador do painel</span><span class="input-wrap"><input name="platformAdminPassword" type="password" autocomplete="current-password" required></span></label><label class="field"><span>Digite <strong>EXCLUIR</strong> para confirmar</span><span class="input-wrap"><input name="confirmation" autocomplete="off" required></span></label>${adminToolError?`<p class="error">${esc(adminToolError)}</p>`:""}<div class="form-actions"><button class="btn danger" type="submit">Autenticar e excluir</button><button class="btn secondary" type="button" data-cancel-delete>Cancelar</button></div></form></section></div>`;return `<div class="admin-modal-backdrop"><section class="admin-modal admin-confirm" role="alertdialog" aria-modal="true"><h2>Confirmar exclusão</h2><p>Deseja realmente excluir <strong>${esc(label)}</strong>?</p><p class="muted">Esta ação não poderá ser desfeita.</p><div class="form-actions"><button class="btn danger" id="confirmDelete">Excluir</button><button class="btn secondary" type="button" data-cancel-delete>Cancelar</button></div></section></div>`}
function adminToolModal(){if(!adminTool)return "";const company=adminTool.company;if(adminTool.type==="password")return `<div class="admin-modal-backdrop user-modal-layer" data-close-admin-tool><section class="admin-modal" role="dialog" aria-modal="true"><button class="admin-modal-close" type="button" data-close-admin-tool aria-label="Fechar">×</button><form class="admin-form" id="cancellationPasswordForm"><h2>Redefinir senha de cancelamento</h2><p class="modal-context">Empresa: <strong>${esc(company.name)}</strong></p><label class="field"><span>Nova senha</span><span class="input-wrap"><input name="password" type="password" minlength="6" maxlength="128" autocomplete="new-password" required autofocus></span></label><label class="field"><span>Confirmar nova senha</span><span class="input-wrap"><input name="confirmation" type="password" minlength="6" maxlength="128" autocomplete="new-password" required></span></label>${adminToolError?`<p class="error">${esc(adminToolError)}</p>`:""}<div class="form-actions"><button class="btn" type="submit">Redefinir senha</button><button class="btn secondary" type="button" data-close-admin-tool>Cancelar</button></div></form></section></div>`;return `<div class="admin-modal-backdrop user-modal-layer" data-close-admin-tool><section class="admin-modal" role="alertdialog" aria-modal="true"><button class="admin-modal-close" type="button" data-close-admin-tool aria-label="Fechar">×</button><form class="admin-form" id="clearCompanyDataForm"><h2>Autorizar limpeza dos dados</h2><p>Esta ação apagará produtos, vendas, caixa, movimentações, históricos, categorias, fornecedores e configurações de <strong>${esc(company.name)}</strong>.</p><p class="muted">A empresa e seus usuários serão preservados. Confirme as credenciais do administrador do painel.</p><label class="field"><span>E-mail do administrador do painel</span><span class="input-wrap"><input name="platformAdminEmail" type="email" autocomplete="username" required autofocus></span></label><label class="field"><span>Senha do administrador do painel</span><span class="input-wrap"><input name="platformAdminPassword" type="password" autocomplete="current-password" required></span></label><label class="field"><span>Digite <strong>LIMPAR</strong> para confirmar</span><span class="input-wrap"><input name="confirmation" autocomplete="off" required></span></label>${adminToolError?`<p class="error">${esc(adminToolError)}</p>`:""}<div class="form-actions"><button class="btn danger" type="submit">Autenticar e limpar dados</button><button class="btn secondary" type="button" data-close-admin-tool>Cancelar</button></div></form></section></div>`}
function render(){const view=section==="administrators"?administratorView():companyView();root.innerHTML=shell(view+(userModalOpen?userModal():"")+confirmationModal()+adminToolModal());document.querySelector("#companyForm [name=adminEmail]")?.closest("label")?.remove();document.querySelector("#logout").onclick=()=>signOut(auth);document.querySelectorAll("[data-section]").forEach(button=>button.onclick=()=>{section=button.dataset.section;editingCompany=null;editingAdministrator=null;editingUser=null;companyModalOpen=false;administratorModalOpen=false;userModalOpen=false;confirming=null;adminTool=null;adminToolError="";message="";render()});bindModalEvents();if(section==="companies")bindCompanyEvents();else bindAdministratorEvents()}
function closeFormModal(){editingCompany=null;editingAdministrator=null;editingUser=null;companyModalOpen=false;administratorModalOpen=false;userModalOpen=false;adminTool=null;adminToolError="";render()}
function bindModalEvents(){document.querySelector("[data-dismiss-message]")?.addEventListener("click",()=>{message="";render()});document.querySelectorAll("[data-close-modal]").forEach(element=>element.onclick=event=>{if(event.target===element||element.tagName==="BUTTON")closeFormModal()});document.querySelectorAll("[data-close-user-modal]").forEach(element=>element.onclick=event=>{if(event.target===element||element.tagName==="BUTTON"){editingUser=null;userModalOpen=false;companyModalOpen=true;render()}});document.querySelectorAll("[data-close-admin-tool]").forEach(element=>element.onclick=event=>{if(event.target===element||element.tagName==="BUTTON"){adminTool=null;adminToolError="";render()}});document.querySelector("[data-cancel-delete]")?.addEventListener("click",()=>{confirming=null;adminToolError="";render()});document.querySelector("#confirmDelete")?.addEventListener("click",async event=>{event.currentTarget.disabled=true;event.currentTarget.textContent="Excluindo...";try{const target=confirming;confirming=null;if(target.type==="user")await removeUser(target.item);else await removeAdministrator(target.item)}catch(error){confirming=null;message=error.message||"Falha ao excluir.";render()}});document.querySelector("#confirmCompanyDeleteForm")?.addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(event.currentTarget),confirmation=String(form.get("confirmation")||"").trim().toUpperCase();if(confirmation!=="EXCLUIR"){adminToolError='Digite "EXCLUIR" para confirmar.';return render()}const button=event.currentTarget.querySelector("button[type=submit]"),company=confirming.item;button.disabled=true;button.textContent="Autenticando...";try{await verifyPlatformAdministrator(form.get("platformAdminEmail"),form.get("platformAdminPassword"));button.textContent="Excluindo...";confirming=null;adminToolError="";await removeCompany(company)}catch(error){if(!confirming)confirming={type:"company",item:company};adminToolError=error.message||"Falha ao autenticar e excluir a empresa.";render()}})}
function bindAdminTools(){document.querySelector("#resetCancellationPassword")?.addEventListener("click",()=>{adminTool={type:"password",company:editingCompany};adminToolError="";render()});document.querySelector("#clearCompanyData")?.addEventListener("click",()=>{adminTool={type:"clear",company:editingCompany};adminToolError="";render()});document.querySelector("#cancellationPasswordForm")?.addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(event.currentTarget),password=String(form.get("password")||""),confirmation=String(form.get("confirmation")||"");if(password.length<6){adminToolError="A senha deve ter pelo menos 6 caracteres.";return render()}if(password!==confirmation){adminToolError="As senhas não conferem.";return render()}const button=event.currentTarget.querySelector("button[type=submit]");button.disabled=true;button.textContent="Redefinindo...";try{await resetCancellationPasswordDirect(adminTool.company.id,password);adminTool=null;adminToolError="";message="Senha de cancelamento redefinida com sucesso."}catch(error){adminToolError=error.message||"Falha ao redefinir a senha de cancelamento."}render()});document.querySelector("#clearCompanyDataForm")?.addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(event.currentTarget),confirmation=String(form.get("confirmation")||"").trim().toUpperCase();if(confirmation!=="LIMPAR"){adminToolError='Digite "LIMPAR" para confirmar.';return render()}const button=event.currentTarget.querySelector("button[type=submit]"),company=adminTool.company;button.disabled=true;button.textContent="Autenticando...";try{await verifyPlatformAdministrator(form.get("platformAdminEmail"),form.get("platformAdminPassword"));button.textContent="Limpando dados...";const deletedDocuments=await clearCompanyDataDirect(company.id);adminTool=null;adminToolError="";message=`Dados de ${company.name} limpos com sucesso. ${deletedDocuments} registros apagados.`}catch(error){adminToolError=error.message||"Falha ao autenticar e limpar os dados da empresa."}render()})}
function bindCompanyEvents(){document.querySelector("#newCompany").onclick=()=>{editingCompany=null;companyModalOpen=true;render()};if(document.querySelector("#companyForm"))document.querySelector("#companyForm").onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector("button[type=submit]");button.disabled=true;button.textContent="Salvando...";try{await saveCompany(event.currentTarget);editingCompany=null;companyModalOpen=false;await load("Empresa salva com sucesso.")}catch(error){message=error.message||"Falha ao salvar empresa.";render()}};document.querySelectorAll("[data-edit-company]").forEach(button=>button.onclick=()=>{editingCompany=companies.find(item=>item.id===button.dataset.editCompany);companyModalOpen=true;render()});document.querySelectorAll("[data-delete-company]").forEach(button=>button.onclick=()=>{adminToolError="";confirming={type:"company",item:companies.find(item=>item.id===button.dataset.deleteCompany)};render()});document.querySelectorAll("[data-toggle-company]").forEach(button=>button.onclick=async()=>{const company=companies.find(item=>item.id===button.dataset.toggleCompany);await updateDoc(doc(db,"companies",company.id),{isActive:company.isActive===false,updatedAt:serverTimestamp()});await load("Status da empresa atualizado.")});document.querySelector("#newCompanyUser")?.addEventListener("click",()=>{editingUser=null;userModalOpen=true;render()});document.querySelectorAll("[data-edit-company-user]").forEach(button=>button.onclick=()=>{editingUser=users.find(user=>user.uid===button.dataset.editCompanyUser);userModalOpen=true;render()});document.querySelectorAll("[data-delete-company-user]").forEach(button=>button.onclick=()=>{confirming={type:"user",item:users.find(user=>user.uid===button.dataset.deleteCompanyUser)};render()});bindAdminTools();bindUserForm()}
function bindAdministratorEvents(){document.querySelector("#newAdministrator").onclick=()=>{editingAdministrator=null;administratorModalOpen=true;render()};if(document.querySelector("#administratorForm"))document.querySelector("#administratorForm").onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector("button[type=submit]");button.disabled=true;button.textContent="Salvando...";try{await saveAdministrator(event.currentTarget);editingAdministrator=null;administratorModalOpen=false;await load("Administrador salvo com sucesso.")}catch(error){message=error.message||"Falha ao salvar administrador.";render()}};document.querySelectorAll("[data-edit-administrator]").forEach(button=>button.onclick=()=>{editingAdministrator=administrators.find(item=>item.uid===button.dataset.editAdministrator);administratorModalOpen=true;render()});document.querySelectorAll("[data-delete-administrator]").forEach(button=>button.onclick=()=>{const item=administrators.find(item=>item.uid===button.dataset.deleteAdministrator);if(item.uid===auth.currentUser?.uid){message="Você não pode excluir a conta administrativa que está usando.";return render()}confirming={type:"administrator",item};render()})}
function bindUserForm(){if(document.querySelector("#userForm"))document.querySelector("#userForm").onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector("button[type=submit]");button.disabled=true;button.textContent="Salvando...";try{await saveUser(event.currentTarget);editingUser=null;userModalOpen=false;companyModalOpen=true;await load("Usuário salvo com sucesso.")}catch(error){message=error.message||"Falha ao salvar usuário.";render()}}}
renderLogin();
onAuthStateChanged(auth,async user=>{if(!user)return renderLogin();try{const access=await getDoc(doc(db,"platform_admins",user.uid));if(!access.exists()||access.data().isActive===false){await signOut(auth);return renderLogin("Esta conta não possui autorização administrativa.")}await load()}catch(error){await signOut(auth).catch(()=>{});renderLogin(error.message||"Não foi possível validar a sessão administrativa.")}});
